//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartments()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_Metro { get; set; }
        public Nullable<int> id_Region { get; set; }
        public string img { get; set; }
        public string Link { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public int Rooms { get; set; }
        public double Area { get; set; }
        public int Floor { get; set; }
        public int Price { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual Metro Metro { get; set; }
        public virtual Region Region { get; set; }

        public Apartments(int id_Metro, int id_Region, string img, string link, string title, string address, int rooms, double area, int floor, int price, string comment, string status)
        {
            this.id_Metro = id_Metro;
            this.id_Region = id_Region;
            this.img = img;
            Link = link;
            Title = title;
            Address = address;
            Rooms = rooms;
            Area = area;
            Floor = floor;
            Price = price;
            Comment = comment;
            Status = status;
        }
    }
}
